### ISSUE TITLE
Base.html not working

### ISSUE THREAD

**Issue by kyawminthu20** [adhikarisarthak/401-Assignment#15]
Base html not working now

**Comment by codingaccount26599** [comment]
Removal of '"{% else %"' from base.html could be related to the issue, when I pushed the project at 4 am, the menu bar was functional and 'shopping list' and 'expired item' pages were working.

**Comment by painayan18** [comment]
I did make some changes to the file, while making login/register pages I think it might've broken the page. looking into it now.

**Comment by kyawminthu20** [comment]
it is fixed. Thank you

**Comment by adhikarisarthak** [comment]
Issue was the block content
